import { Link } from 'react-router-dom'
import { Icon } from '../components/Icons'
import SectionHeader from '../components/SectionHeader'

export default function Partners() {
  const partnerTypes = [['rupee','Financing partners','Banks and NBFCs looking for purchase-linked access to underserved rural customers.',['Verified transactions','Merchant-led sourcing','Digital repayment trail']],['store','Merchant partners','Agri-input retailers ready to grow sales and modernize customer credit.',['Faster checkout','Better records','Lower credit exposure']],['zap','Technology partners','Infrastructure providers helping make rural transactions safe, fast and interoperable.',['API-first approach','Focused integrations','Shared impact']]]
  return <>
    <section className="page-hero partners-hero"><div className="container page-hero-grid"><div><span className="eyebrow">PARTNER WITH AGRIPAY</span><h1>Rural growth is<br/><em>a team effort.</em></h1><p>We bring merchants, financial institutions and technology providers together around one transparent transaction.</p><Link className="button" to="/contact">Explore a partnership <Icon name="arrow" size={18}/></Link></div><div className="partner-orbit"><div className="orbit-core"><Icon name="leaf"/><strong>AgriPay</strong></div><span className="orbit-node n1"><Icon name="rupee"/><b>Finance</b></span><span className="orbit-node n2"><Icon name="store"/><b>Merchants</b></span><span className="orbit-node n3"><Icon name="zap"/><b>Technology</b></span></div></div></section>
    <section className="section"><div className="container"><SectionHeader eyebrow="OUR ECOSYSTEM" center title={<>Different strengths.<br/><span className="accent">One shared outcome.</span></>}/><div className="partner-type-grid">{partnerTypes.map(p=><article key={p[1]}><span className="big-icon"><Icon name={p[0]} size={30}/></span><h3>{p[1]}</h3><p>{p[2]}</p><ul>{p[3].map(x=><li key={x}><Icon name="check" size={16}/>{x}</li>)}</ul></article>)}</div></div></section>
    <section className="section advantage"><div className="container"><SectionHeader eyebrow="OUR POSITION" title={<>Not another lender.<br/><span className="accent">The layer that connects them.</span></>} copy="AgriPay focuses on the moment a rural purchase happens — creating the trusted data and workflows that marketplaces, payment platforms and lenders need."/><div className="comparison"><div className="comparison-head"><span>Company</span><span>Primary focus</span><span>Where AgriPay differs</span></div>{[['Jai Kisan','Rural lending','Checkout infrastructure'],['DeHaat','Agri marketplace','Merchant-first platform'],['BharatPe','Merchant payments','Purchase-linked rural credit'],['AgriPay','Rural checkout infrastructure','The connecting layer']].map((r,i)=><div className={i===3?'highlight':''} key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span>{r[2]}</span></div>)}</div></div></section>
    <section className="section business-model"><div className="container business-grid"><div><span className="eyebrow lime">BUSINESS MODEL</span><h2>Built for aligned, sustainable value.</h2><p>Our revenue grows when the ecosystem transacts successfully — keeping incentives aligned across the network.</p></div><div className="revenue-list">{['Transaction fees','Merchant subscriptions','Financing partner commission','Credit analytics','Embedded financial services'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>
    <section className="cta-band"><div className="container"><div><span className="eyebrow lime">BUILD WITH US</span><h2>Let’s unlock rural commerce together.</h2></div><Link className="button button-light" to="/contact">Become a partner <Icon name="arrow" size={18}/></Link></div></section>
  </>
}
